### ISSUE TITLE
Errors in the Docker image when selecting Camera in the simulator first track

### ISSUE THREAD

**Issue by ibrahim-mo** [udacity/CarND-Capstone#147]
After running 'roslaunch launch/styx.launch' from the Docker image while the simulator is running and the connection is established, then once I click on the camera check box, I get thse errors in ros (the errors are repetitive as long as there's a connection):
```
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 405, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 509, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 448, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 451, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 480, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/capstone/ros/src/styx/server.py", line 60, in image
    bridge.publish_camera(data)
  File "/capstone/ros/src/styx/bridge.py", line 182, in publish_camera
    image_message = self.bridge.cv2_to_imgmsg(image_array, encoding="rgb8")
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/core.py", line 248, in cv2_to_imgmsg
    img_msg.height = cvim.shape[0]
IndexError: tuple index out of range
```
FYI, I am running the Docker image on MacBook Pro (I tired two different Macs) both running MacOS Sierra.

**Comment by kliu99** [comment]
uninstall pillow 2.x, and reinstall for version 4.3

`pip uninstall Pillow`
`pip install Pillow`

**Comment by ibrahim-mo** [comment]
This fixes the issue. Thanks a lot!

**Comment by ibrahim-mo** [comment]
Perhaps you should consider updating this in the requirements.txt file.

**Comment by papiot** [comment]
This saved my day!

**Comment by KansaiUser** [comment]
> uninstall pillow 2.x, and reinstall for version 4.3
> 
> `pip uninstall Pillow`
> `pip install Pillow`

I will try this but I wonder where are you specifying the versions in the comments above. 

And second question, what is that "camera" option for in the simulator?

**Comment by KansaiUser** [comment]
Why this has not been incorporated in the master branch is beyond me. It solved it for me

```
pip uninstall Pillow
pip install Pillow==4.3
```

**Comment by UAnjali** [comment]
Hi @ibrahim-mo,
We are closing out the issue because it has already been addressed in another issue recently.
