### ISSUE TITLE
Socket Timeout while running  roslaunch launch/styx.launch in Ubuntu 14.04.5

### ISSUE THREAD

**Issue by vikashranjan** [udacity/CarND-Capstone#153]
I followed the installation instructions for Ubuntu 14.04.5  however when I run After running 'roslaunch launch/styx.launch' I get socket.timeout Exception. I am unable to proceed further .

```auto-starting new master
process[master]: started with pid [19241]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 16369e3c-f61c-11e7-b7b8-10feed1aa417
process[rosout-1]: started with pid [19254]
started core service [/rosout]
process[styx_server-2]: started with pid [19262]
process[unity_simulator-3]: started with pid [19272]
What is the full path to your Unity simulator?
process[dbw_node-4]: started with pid [19276]
process[waypoint_loader-5]: started with pid [19277]
process[pure_pursuit-6]: started with pid [19278]
process[waypoint_updater-7]: started with pid [19279]
process[tl_detector-8]: started with pid [19283]
(19262) wsgi starting up on http://0.0.0.0:4567
(19262) wsgi exited, is_accepting=True
Traceback (most recent call last):
  File "/home/vikash/CarND-Capstone/ros/src/styx/server.py", line 68, in <module>
    eventlet.wsgi.server(eventlet.listen(('', 4567)), app)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 896, in server
    client_socket = sock.accept()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 224, in accept
    self._trampoline(fd, read=True, timeout=self.gettimeout(), timeout_exc=_timeout_exc)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 207, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 163, in trampoline
    return hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
socket.timeout: timed out
[WARN] [WallTime: 1515598676.756611] Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[styx_server-2] process has died [pid 19262, exit code 1, cmd /home/vikash/CarND-Capstone/ros/src/styx/server.py __name:=styx_server __log:=/home/vikash/.ros/log/16369e3c-f61c-11e7-b7b8-10feed1aa417/styx_server-2.log].
log file: /home/vikash/.ros/log/16369e3c-f61c-11e7-b7b8-10feed1aa417/styx_server-2*.log
```

**Comment by vikashranjan** [comment]
Resolved.
