### ISSUE TITLE
interface between ros point cloud 2 and obstacle data out of simulator seems not fit

### ISSUE THREAD

**Issue by chilisy** [udacity/CarND-Capstone#213]
I've got following error whenever I started the simulator and launch stxy:
```
message handler error
Traceback (most recent call last):
  File "/home/chili/.local/lib/python2.7/site-packages/engineio/server.py", line 408, in _trigger_event
    return self.handlers[event](*args)
  File "/home/chili/.local/lib/python2.7/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/chili/.local/lib/python2.7/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/home/chili/.local/lib/python2.7/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/chili/.local/lib/python2.7/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/chili/Dokumente/CarND-Capstone/ros/src/styx/server.py", line 48, in obstacle
    bridge.publish_obstacles(data)
  File "/home/chili/Dokumente/CarND-Capstone/ros/src/styx/bridge.py", line 156, in publish_obstacles
    cloud = pcl2.create_cloud_xyz32(header, data['obstacles'])
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/point_cloud2.py", line 165, in create_cloud_xyz32
    return create_cloud(header, fields, points)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/point_cloud2.py", line 138, in create_cloud
    pack_into(buff, offset, *p)
error: pack_into expected 3 items for packing (got 6)
```
What went wrong with my installation?

**Comment by chilisy** [comment]
The German ubuntu system cause this error.
