### ISSUE TITLE
AttributeError: 'SteeringReport' object has no attribute 'steering_wheel_angle_cmd'

### ISSUE THREAD

**Issue by SmokeShine** [udacity/CarND-Capstone#314]
Not able to communicate to simulator. Using docker build on local setup.
```
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 544, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 509, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 448, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 451, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 480, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/capstone/ros/src/styx/server.py", line 44, in control
    bridge.publish_controls(data)
  File "/capstone/ros/src/styx/bridge.py", line 145, in publish_controls
    self.publishers['steering_report'].publish(self.create_steer(steering))
  File "/capstone/ros/src/styx/bridge.py", line 102, in create_steer
    st.steering_wheel_angle_cmd = val * math.pi/180.
AttributeError: 'SteeringReport' object has no attribute 'steering_wheel_angle_cmd'
```

Tried manually downgrading to 1.1.1*. Version does not exist anymore
```
root@5b2d1a45b46d:/capstone/ros# sudo apt list -a ros-$ROS_DISTRO-dbw-mkz
Listing... Done
ros-kinetic-dbw-mkz/unknown 1.2.5-0xenial-20191030-163434+0000 amd64 [upgradable from: 1.2.3-1xenial-20191024-181843+0000]
ros-kinetic-dbw-mkz/xenial,now 1.2.3-1xenial-20191024-181843+0000 amd64 [installed,upgradable to: 1.2.5-0xenial-20191030-163434+0000]
```
Downgrade command
```
sudo apt-get install ros-$ROS_DISTRO-dbw-mkz=1.1.1* ros-$ROS_DISTRO-dbw-mkz-msgs=1.1.1* ros-$ROS_DISTRO-dbw-mkz-can=1.1.1* ros-$ROS_DISTRO-dbw-mkz-description=1.1.1* ros-$ROS_DISTRO-dbw-mkz-joystick-demo=1.1.1*
```

**Comment by Horki** [comment]
@SmokeShine  can be fixed by adding manually *dbw_mkz_msgs* into ros/src, like here

https://github.com/Horki/CarND-Capstone/tree/master/ros/src/dbw_mkz_msgs

**Comment by UAnjali** [comment]
Hi @SmokeShine,
We are closing out the issue because it has already been addressed in this [PR](https://github.com/udacity/CarND-Capstone/pull/296).

**Comment by Horki** [comment]
@UAnjali I was prepared to celebrate two years anniversary of this ticket
