### ISSUE TITLE
Keras 1.2.0 InceptionV3 issue when using TensorFlow 1.0.0

### ISSUE THREAD

**Issue by mreichelt** [udacity/CarND-Capstone#96]
Our team has the following issue when trying to re-train an InceptionV3 net or running a pre-trained InceptionV3 net with the requirements `keras==1.2.0` and `tensorflow==1.0.0`:

```
loading traffic light detector model
Traceback (most recent call last):
  File "/udacity/ros/src/tl_detector/tl_detector.py", line 295, in <module>
    TLDetector()
  File "/udacity/ros/src/tl_detector/tl_detector.py", line 51, in __init__
    self.light_classifier = TLClassifier()
  File "/udacity/ros/src/tl_detector/light_classification/tl_classifier.py", line 23, in __init__
    self.model = keras.models.load_model(model_path)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/models.py", line 140, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/models.py", line 190, in model_from_config
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 38, in layer_from_config
    return layer_class.from_config(config['config'], custom_objects=custom_objects)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 2575, in from_config
    process_layer(layer_data)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 2572, in process_layer
    layer(input_tensors)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1452, in __call__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 170, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1388, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/home/udacity/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1222, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

The effect is that we can not use transfer learning using Keras, which we think is a major setback for all Capstone teams.

The issue is also discussed in this upstream Keras issue: https://github.com/fchollet/keras/issues/3548

We can solve this issue by upgrading Keras to version 1.2.2 locally, but we would need the same version running on Carla to be able to submit the project.

**Comment by mreichelt** [comment]
Added PR to set Keras version to 1.2.2: https://github.com/udacity/CarND-Capstone/pull/97

**Comment by mreichelt** [comment]
Closed because Keras has already been upgraded to 2.x.
